# Generated by Django 3.1.5 on 2021-01-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('Musician_id', models.AutoField(primary_key=True, serialize=False)),
                ('Musician_name', models.CharField(max_length=100)),
                ('Site', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('Song_id', models.AutoField(primary_key=True, serialize=False)),
                ('Song_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
                ('Musician_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.musician')),
            ],
        ),
    ]
