# Generated by Django 3.1.5 on 2021-01-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0004_auto_20210112_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.CharField(default='текст песни', max_length=300),
        ),
    ]
