# Generated by Django 3.1.5 on 2021-01-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0006_auto_20210112_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.CharField(default='текст песни', max_length=5000),
        ),
    ]
