# Generated by Django 3.1.5 on 2021-01-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0007_auto_20210112_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(),
        ),
    ]
