# Generated by Django 3.1.5 on 2021-01-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0008_auto_20210112_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterField(
            model_name='musician',
            name='Musician_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID музыканта'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='Musician_name',
            field=models.CharField(max_length=100, verbose_name='Имя музыканта/название группы'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='Site',
            field=models.CharField(max_length=200, verbose_name='Сайт музыканта'),
        ),
        migrations.AlterField(
            model_name='song',
            name='Musician_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.musician', verbose_name='Исполнитель песни'),
        ),
        migrations.AlterField(
            model_name='song',
            name='Song_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID песни'),
        ),
        migrations.AlterField(
            model_name='song',
            name='Song_name',
            field=models.CharField(max_length=100, verbose_name='Название песни'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Длительность песни'),
        ),
        migrations.AlterField(
            model_name='song',
            name='img',
            field=models.CharField(max_length=100, verbose_name='Файл обложки'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(verbose_name='Текст песни'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default=1, verbose_name='ID исполнителя'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_link',
            field=models.CharField(default='ссылка на mp3', max_length=200, verbose_name='Файл песни'),
        ),
    ]
