# Generated by Django 3.1.5 on 2021-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0009_auto_20210112_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(default='описание песни', verbose_name='Опрсание песни'),
        ),
    ]
